name: Update stars count

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at 00:00

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node with version 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Run script
        uses: ./.github/actions/update-stars
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run format
        run: npm run format
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: github_actions
          commit-message: "(AUTO) Update stars"
          title: "BOT: Update stars"
          body: Update all stars count from Github and Gitlab
          branch: ci-update-stars
          add-paths: src/lib/stars.json
          delete-branch: true
